### ISSUE TITLE
*.aspx not ignored for compilation in Release-Build

### ISSUE THREAD

**Issue by micmerchant** [CZEMacLeod/MSBuild.SDK.SystemWeb#22]
Hello,

we are currently migrating our ASP.NET Web Application from the old csproj format to the new SDK-Style Project format, but we are facing an issue with Release-Builds. It seems that *.aspx files can't be ignored for compilation by the
DefaultItemExcludes/ItemGroup directives. *.cs files for example are properly ignored.

The interessting thing is, that this happens only in Release-Builds. Debug-Builds aren't affacted.

I've attached a simple example solution. 

Thanks in advance,
BR Michael
[WebApplication2.zip](https://github.com/CZEMacLeod/MSBuild.SDK.SystemWeb/files/7116440/WebApplication2.zip)

**Comment by CZEMacLeod** [comment]
Hi - I'm guessing this is caused because the [`AspNetCompiler`](https://docs.microsoft.com/en-us/visualstudio/msbuild/aspnetcompiler-task?view=vs-2019) task is invoked when in release mode.
I don't believe there is any way to pass explicit file paths to include or exclude to this task unfortunately (I think it mainly just wraps the [`Aspnet_compiler.exe`](https://docs.microsoft.com/en-us/previous-versions/ms229863(v=vs.100)).

The easy way to avoid this is to set the `MvcBuildViews` property to false in your project file and it won't then invoke this [task/target](https://github.com/CZEMacLeod/MSBuild.SDK.SystemWeb/blob/3fbb47db60c1bcb29982edd938892a9380d814ae/src/MSBuild.SDK.SystemWeb/Sdk/Sdk.targets#L16) during release builds.

```xml
<PropertyGroup>
   <MvcBuildViews>false</MvcBuildViews>
</PropertyGroup>
```

I think this is probably the same behaviour you would get in the original Web Application templates if MVC is selected. The templates in this project don't have quite the same nuances of being able to specify WebForms, MVC, and/or WebAPI so pretty much try to cover everything in one go.

**Comment by micmerchant** [comment]
Thank you, this solves our problem.
