### ISSUE TITLE
Support for C# 10?

### ISSUE THREAD

**Issue by Bouke** [CZEMacLeod/MSBuild.SDK.SystemWeb#28]
I'm using C# 10 in my ASP.NET WebApplication (`<LangVersion>10</LangVersion>`). Using this SDK it seems this is not possible:

>  Invalid option '10' for /langversion. Use '/langversion:?' to list supported values.

Is there a way to make this work? FWIW I am building other libraries against .NET Framework 4.8 with C# 10.

**Comment by Bouke** [comment]
I've added the latest version of that package, but the error remains.

```xml
    <PackageReference Update="Microsoft.Net.Compilers.Toolset" Version="4.0.1" />
```

**Comment by CZEMacLeod** [comment]
The SDK pulls in 
```xml
<PackageReference Include="Microsoft.Net.Compilers.Toolset" Version="3.8.0" PrivateAssets="All"/>
```
automatically - as well as 
```xml
<PackageReference Include="Microsoft.CodeDom.Providers.DotNetCompilerPlatform" Version="3.6.0" />
```
unless you set the property `ExcludeASPNetCompilers` to true.

If you are using `Microsoft.Build.CentralPackageVersions` you can actually set these versions in your central packages file.

Because of the order, if you place it in your project file, I'm pretty sure your 
```xml
    <PackageReference Update="Microsoft.Net.Compilers.Toolset" Version="4.0.1" />
```
happens _before_ the include so there will be nothing to update at that point.
If you move that to `Directory.Build.targets` it _should_ work though.

Alternatively use
```xml
<PropertyGroup>
    <ExcludeASPNetCompilers>true</ExcludeASPNetCompilers>
</PropertyGroup>
<ItemGroup>
    <PackageReference Include="Microsoft.Net.Compilers.Toolset" Version="4.0.1" PrivateAssets="All"/>
    <PackageReference Include="Microsoft.CodeDom.Providers.DotNetCompilerPlatform" Version="3.6.0" />
</ItemGroup>
```

I will also look at potentially updating the default version pulled in by the SDK to 4.0.1.

I'm not entirely sure if there is an updated version of the CodeDom Providers, which means the langversion available in your compiled pages might not support C# 10.

**Comment by Bouke** [comment]
Using version 4.0.66 with `<MicrosoftNetCompilersToolset_Version>4.0.1</MicrosoftNetCompilersToolset_Version>` gets rid of that error 👍. Thank you for your time and investigation.

---

Sadly I'm running into another issue which I hoped to get rid off by switching to Sdk-style project in the first place. My project builds fine on Windows (old-style csproj), but fails to build on macOS/Mono with the following error. I don't understand why this happens as `MyLibrary` builds just fine.

>  Assembly 'MyLibrary' with identity 'MyLibrary, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' uses 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' which has a higher version than referenced assembly 'System.Net.Http' with identity 'System.Net.Http, Version=4.1.1.3, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

**Comment by slang25** [comment]
That brings back some bad memories. I think this SO answer might help:
https://stackoverflow.com/a/51424880/2225808

**Comment by Bouke** [comment]
Yes bad memories indeed. I thought I left those behind by migrating to PackageReference and auto binding redirects. And it has been working fine for years now on Windows (regular Framework 4.8).

Thanks for the suggestion. My project already has a transitive dependency on System.Buffers 4.5.1, and making that dependency explicit doesn't resolve the build warning. I suspect the bug is with Mono not resolving the System.Net.Http dependencies similar to framework v4.7.2 or 4.8, but I have yet to find proof of this.

**Comment by CZEMacLeod** [comment]
@Bouke Since the update to 4.0.66 deals with the c#10 issue, do you mind closing this?
If there is something specific to the SDK which affects your binding redirects / package resolving process perhaps open a new issue about it.
It should be noted, that using this on Linux/Mac with Mono is not really a supported scenario for this SDK and you are in for many other difficulties I suspect.
