### ISSUE TITLE
Use MSBuild.Microsoft.VisualStudio.Web.targets nuget instead of direct reference from Visual Studio installation

### ISSUE THREAD

**Issue by gickis** [CZEMacLeod/MSBuild.SDK.SystemWeb#29]
I think would be better to migrate reference of Microsoft.WebApplication.targets from installed Visual Studio to nuget package. In this case developers will be able to build their applications in Linux environments (for instance on linux build agents)

**Comment by gickis** [comment]
You are right. My bad. I guess we can close this issue right now. Thanks for pointing me to "not official nuget package"

**Comment by CZEMacLeod** [comment]
@slang25 Thanks for pointing this out - I did actually look to see if there was an official package for this when I was building the SDK but couldn't find one.
It would be nice if there were as it would mean that you could lock the version instead of relying on whichever version was installed (or not installed) on your build server.
