### ISSUE TITLE
TypeScript Compilation with Microsoft.TypeScript.MSBuild not working

### ISSUE THREAD

**Issue by spencer-wcri** [CZEMacLeod/MSBuild.SDK.SystemWeb#86]
[Microsoft.TypeScript.MSBuild nuget package](https://www.nuget.org/packages/Microsoft.TypeScript.MSBuild#readme-body-tab) compiles typescript as part of the project build. 
The [usage is straightforward](https://learn.microsoft.com/en-us/visualstudio/javascript/compile-typescript-code-nuget?view=vs-2022#remove-default-imports), just a package reference and a tsconfig.json.

However, I'm having troubles getting it working with this SystemWeb sdk target.

Any ideas on I can get Microsoft.TypeScript.MSBuild to play nice with the SystemWeb sdk type?

## Things I've tried

I've run several experiments. I can confirm that [these instructions](https://learn.microsoft.com/en-us/visualstudio/javascript/compile-typescript-code-nuget?view=vs-2022#remove-default-imports) successfully compile typescript in
- a default Asp.Net core MVC template 
- a .net 8 class library
- a net472 class library on sdk style

Adding Microsoft.TypeScript.MSBuild to a classic non-sdk style Asp.Net project using the Visual Studio nuget package UI also successfully compiles TypeScript during the project build. 

Examining the project file, installing Microsoft.TypeScript.MSBuild to a non-sdk project adds these two import statements
```xml
<Import Project="..\packages\Microsoft.TypeScript.MSBuild.2.4.1\build\Microsoft.TypeScript.MSBuild.props"
 Condition="Exists('..\packages\Microsoft.TypeScript.MSBuild.2.4.1\build\Microsoft.TypeScript.MSBuild.props')" />

<Import Project="..\packages\Microsoft.TypeScript.MSBuild.2.4.1\build\Microsoft.TypeScript.MSBuild.targets" 
 Condition="Exists('..\packages\Microsoft.TypeScript.MSBuild.2.4.1\build\Microsoft.TypeScript.MSBuild.targets')" />
```
However, installing the nuget package and adding these imports to a template SystemWeb project does not similarly enable typescript compilation.

Update: I realized these Import tags expect nuget to create a packages directory, but SystemWeb with PackageReference doesn't do that. I found absolute paths to the prop and target files and updated the import tags. Unfortunately that didn't work either.

**Comment by CZEMacLeod** [comment]
I can't replicate any issue with this.
You simply add the package as normal for an SDK project (e.g. copy from the nuget package page).

I created an example project using the template and added a couple of TS files (including one with an error) and the build files work including showing errors.

I only had to add that I wanted to include the *.js output files as content to the template (along with the package reference) - and this step was not strictly required for testing - only for publishing.

https://github.com/CZEMacLeod/SystemWeb-SDK-with-TypeScript

```xml
  <ItemGroup>
    <PackageReference Include="Microsoft.TypeScript.MSBuild" Version="5.6.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <Content Include="Scripts\**\*.js" />
  </ItemGroup>
```

Please provide an example project that doesn't work.

N.B. In (all) SDK projects, you don't need to add the imports for the .props/.targets files in nuget packages - they are imported automatically.

If you want to - check the imports section when you select to show hidden files in the solution explorer...
![image](https://github.com/user-attachments/assets/c3a38f1d-3ecd-458b-af85-a4bc810dc85d)
![image](https://github.com/user-attachments/assets/c208d8ca-f48b-4bcf-a5a1-e37969944315)

**Comment by spencer-wcri** [comment]
Thanks for the insight!

The problem seems to be our TypeScript version.

I cloned your example and changed the import to 
```xml

  <PackageReference Include="Microsoft.TypeScript.MSBuild" Version="2.4.1">
    <PrivateAssets>all</PrivateAssets>
    <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
  </PackageReference>
```
That was enough to break the build.

Conversely, updating my own example project to Microsoft.TypeScript.MSBuild 5.6.2 fixed my build.

The package version is supposed to correspond to the typescript version, 
so it looks like we'll have to bite the bullet on updating our typescript.

Thanks again!

**Comment by CZEMacLeod** [comment]
Looking at the TypeScript documentation [Compiler Options in MSBuild](https://www.typescriptlang.org/docs/handbook/compiler-options-in-msbuild.html#toolsversion) it looks like you can force the tools version seperately from the MSBuild version:

```xml
  <PropertyGroup>
    <TypeScriptToolsVersion>2.4</TypeScriptToolsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.TypeScript.MSBuild" Version="5.6.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <Content Include="Scripts\**\*.js" />
  </ItemGroup>
```

**Comment by spencer-wcri** [comment]
Looking at detailed build logs, it looks like the Microsoft.TypeScript.MSBuild package is overwriting `TypeScriptToolsVersion`.
We hypothesize that `TypeScriptToolsVersion` is an artifact of some other approach, but we haven't clearly identified its usage yet.

Also, I gathered up my experiments and published them to a repo. 
https://github.com/WesternCapital/TSCompile-SystemWeb-Experiment

It looks like the build might not be as smooth with Asp.Net as I thought. 
I had `"compileOnSave": true,` in the tsconfig, which I think led me to think Asp.Net Core and Classic Asp.Net were building out of the box with Microsoft.TypeScript.MSBuild 2.4.1. When clean up the examples, I noticed that both vanilla Asp.Net projects were not building. The class libraries still build with 2.4.1.

**Comment by leusbj** [comment]
I noticed a couple things that might shed some light on the odd behaviors you are seeing
* In the `TSCompile-AspCore` sample explicitly set the "Build Action/ItemGroup" of the `tsconfig.json` to `None` instead of `Content`
* In the `TSCompile-classlib` sample explicitly set the "Build Action/ItemGroup" of the `tsconfig.json` to `None` instead of `Content`
* In the `TSCompile-classlib-net4` sample explicitly set the "Build Action/ItemGroup" of the `tsconfig.json` to `None` instead of `Content`
* In the `TSCompile-SystemWeb-Experiment` sample did not have a `tsconfig.json` file at all


During the build, the TypeScript engine looks for a `tsconfig.json` file, it only looks in the `Content` ItemGroup, not the `None` (Not sure why they made it that way, but you can check the `FindConfigFiles` target in the `Microsoft.TypeScript.targets`  file), so in all the above cases , it ran as if it did not have a `tsconfig.json` file.

When the build runs WITH a `tsconfig.json` it assumes the developer used the appropriate settings in the config file to choose the desired .ts files, and performs a preCompute step to look under the project root directory for files that satisfy the config file settings, and then passes those through to the `CompileTypeScriptWithTSConfig` target

When the build runs WITHOUT a `tsconfig.json` it requires that all desired .ts files be included to the `TypeScriptCompile` ItemGroup and if that ItemGroup is empty then the `CompileTypeScript` target is completely skipped. (Note that the 2.4.1 version of the package does not make the `TypeScriptCompile` ItemGroup available so it will be empty).


Although long term you likely want to be looking to upgrade, in the short term I think you can still get the 2.4.1 version working for you with one of the following

If your real project uses `tsconfig.json` already, ensure that it is `Content` (not `None`)

If you do not have one, consider incorporating one, ensuring that it is `Content` (not `None`)

If you do not want to add a `tsconfig.json` consider the following project file tweak that will need to be removed later when you do upgrade TypeScript Compiler. Which will allow you to set the "Build Action/ItemGroup" for all your desired .ts files so tehy can be found during build.

```
<ItemGroup>
  <AvailableItemName Include="TypeScriptCompile" /?
</ItemGroup>
```

**Comment by spencer-wcri** [comment]
Wow. I did not expect that the tsconfig.json had to have a Content build action.
That did it though! Thank you!
